name: Add To GitHub Projects Beta
description: Automatically add issues and PRs to GitHub projects beta
author: GitHub
branding:
  icon: table
inputs:
  project-url:
    required: true
    description: URL of the project to add issues to
  github-app-id:
    required: true
    description: A GitHub app id
  github-app-private-key:
    required: true
    description: A GitHub app private key
  github-app-installation-id:
    required: true
    description: The GitHub app's installation id for the org owning the project
  labeled:
    required: false
    description: A comma-separated list of labels to use as a filter for issue to be added
  label-operator:
    required: false
    description: The behavior of the labels filter, AND to match all labels, OR to match any label (default is OR)
  assigned:
    required: false
    description: A comma-separated list of assignees to use as a filter for issue to be added
  assignee-operator:
    required: false
    description: The behavior of the assigned filter, AND to match all assignees, OR to match any assignee (default is OR)
runs:
  using: 'node16'
  main: 'dist/index.js'
